from enum import Enum

class UIState(Enum):
    BOOT = "BOOT"
    PAIRING = "PAIRING"
    CONNECTING = "CONNECTING"
    READY = "READY"
    LISTENING = "LISTENING"
    THINKING = "THINKING"
    SPEAKING = "SPEAKING"
    WEATHER = "WEATHER"
    TASKS = "TASKS"
    NOTE = "NOTE"
    OFFLINE = "OFFLINE"
    ERROR = "ERROR"
    CAMERA_READY = "CAMERA_READY"
    CAMERA_TAKING_PHOTO = "CAMERA_TAKING_PHOTO"
    CAMERA_PHOTO_SAVED = "CAMERA_PHOTO_SAVED"
    CAMERA_RECORDING = "CAMERA_RECORDING"
    CAMERA_UPLOADING = "CAMERA_UPLOADING"
    CAMERA_VIDEO_SAVED = "CAMERA_VIDEO_SAVED"
    CAMERA_ERROR = "CAMERA_ERROR"
    CAMERA_UPLOAD_FAILED = "CAMERA_UPLOAD_FAILED"

